=== xxddff/homeassistant-powercalc/profile_library/model_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "model.json describes a number of devices, typically lights, for use within the HomeAssistant Powercalc extension.",
  "type": "object",
  "required": [
    "name",
    "device_type",
    "measure_method",
    "measure_device",
    "calculation_strategy",
    "created_at"
  ],
  "properties": {
    "aliases": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Aliases for this model"
    },
    "legacy_ids": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Legacy canonical model ids which should migrate to this model"
    },
    "compatible_integrations": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "List of compatible integrations for this model"
    },
    "author": {
      "type": "string",
      "deprecated": true
    },
    "author_info": {
      "type": "object",
      "description": "Info about the contributor of the profile",
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the contributor"
        },
        "email": {
          "type": "string",
          "description": "Email address of the contributor"
        },
        "github": {
          "type": "string",
          "description": "GitHub username of the contributor"
        }
      },
      "required": [
        "name",
        "github"
      ]
    },
    "calculation_enabled_condition": {
      "type": "string",
      "description": "Template which can be evaluated."
    },
    "calculation_strategy": {
      "type": "string",
      "enum": [
        "lut",
        "linear",
        "fixed",
        "multi_switch",
        "composite"
      ],
      "description": "Supported calculation strategies"
    },
    "composite_config": {
      "oneOf": [
        {
          "type": "array",
          "description": "Configuration for composite calculation strategy",
          "items": {
            "type": "object",
            "properties": {
              "condition": {
                "$ref": "#/definitions/condition"
              }
            }
          }
        },
        {
          "type": "object",
          "properties": {
            "mode": {
              "type": "string",
              "enum": [
                "sum_all",
                "stop_at_first"
              ]
            },
            "strategies": {
              "type": "array",
              "description": "Configuration for composite calculation strategy",
              "items": {
                "type": "object",
                "properties": {
                  "condition": {
                    "$ref": "#/definitions/condition"
                  }
                }
              }
            }
          },
          "required": [
            "mode",
            "strategies"
          ]
        }
      ]
    },
    "config_flow_discovery_remarks": {
      "type": "string",
      "description": "Some remarks to show in the GUI config flow on first step of discovery"
    },
    "config_flow_sub_profile_remarks": {
      "type": "string",
      "description": "Some remarks to show in the GUI config flow on sub profile selection step"
    },
    "created_at": {
      "type": "string",
      "format": "date-time",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$",
      "description": "Creation date of the profile"
    },
    "description": {
      "type": "string",
      "description": "A short description of the device"
    },
    "device_type": {
      "type": "string",
      "enum": [
        "camera",
        "cover",
        "fan",
        "generic_iot",
        "light",
        "power_meter",
        "printer",
        "smart_dimmer",
        "smart_switch",
        "smart_speaker",
        "television",
        "network",
        "vacuum_robot",
        "lawn_mower_robot",
        "heating",
        "ups"
      ],
      "description": "Type of device"
    },
    "discovery_by": {
      "type": "string",
      "enum": [
        "device",
        "entity"
      ],
      "description": "Whether to discover the profile by device or entity"
    },
    "fields": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string",
            "description": "Description of the field"
          },
          "label": {
            "type": "string",
            "description": "Label of the field"
          },
          "selector": {
            "type": "object",
            "properties": {
              "entity": {
                "type": "object",
                "properties": {
                  "domain": {
                    "type": "string"
                  },
                  "device_class": {
                    "type": "string"
                  }
                }
              },
              "number": {
                "type": "object",
                "properties": {
                  "min": {
                    "type": "number"
                  },
                  "max": {
                    "type": "number"
                  }
                }
              }
            }
          }
        }
      }
    },
    "fixed_config": {
      "type": "object",
      "description": "Configuration for fixed calculation strategy",
      "properties": {
        "power": {
          "type": [
            "number",
            "string"
          ]
        },
        "states_power": {
          "type": "object",
          "description": "A dict of state attributes and the power. See https://github.com/bramstroker/homeassistant-powercalc#power-per-state.",
          "properties": {
            "idle": {
              "type": [
                "number",
                "string"
              ]
            },
            "playing": {
              "type": [
                "number",
                "string"
              ]
            },
            "paused": {
              "type": [
                "number",
                "string"
              ]
            },
            "off": {
              "type": [
                "number",
                "string"
              ]
            },
            "unavailable": {
              "type": [
                "number",
                "string"
              ]
            }
          },
          "additionalProperties": {
            "type": [
              "number",
              "string"
            ]
          }
        }
      }
    },
    "is_dumb_bulb": {
      "type": "boolean",
      "description": "The profile is for a dumb light bulb, not having smart capabilities"
    },
    "name": {
      "type": "string",
      "description": "The full name"
    },
    "measure_method": {
      "type": "string",
      "enum": [
        "manual",
        "script"
      ],
      "description": "How the device was measured"
    },
    "measure_description": {
      "type": "string",
      "description": "Add more information about how you measured the device or any remarks"
    },
    "measure_device": {
      "type": "string",
      "description": "Device which was used to measure"
    },
    "measure_device_firmware": {
      "type": "string",
      "description": "Firmware version of the device used to measure"
    },
    "measure_settings": {
      "type": "object",
      "description": "Settings used for measure script"
    },
    "min_version": {
      "type": "string",
      "description": "Minimum required version of Powercalc for this profile"
    },
    "linear_config": {
      "type": "object",
      "description": "Configuration for linear calculation strategy",
      "properties": {
        "min_power": {
          "type": "number"
        },
        "max_power": {
          "type": "number"
        },
        "calibrate": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "linked_lut": {
      "type": "string",
      "description": "Use LUT data files from another model",
      "deprecated": true
    },
    "linked_profile": {
      "type": "string",
      "description": "Use data from another model"
    },
    "only_self_usage": {
      "type": "boolean",
      "description": "Indicates if profile only provides power usage for the device itself"
    },
    "playbook_config": {
      "type": "object",
      "description": "Configuration for playbook calculation strategy",
      "properties": {
        "playbooks": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "description": "Key-value pairs where the key is a playbook ID and the value is the filename."
        },
        "autostart": {
          "type": "string",
          "description": "The playbook ID to autostart."
        },
        "repeat": {
          "type": "boolean",
          "description": "Indicates if the playbook should repeat."
        },
        "state_trigger": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "description": "Start given playbook when entity state changes to given value."
        }
      },
      "required": [
        "playbooks"
      ]
    },
    "sensor_config": {
      "type": "object",
      "description": "Sensor configuration options. See the README"
    },
    "standby_power": {
      "type": "number",
      "minimum": 0.05,
      "description": "Power draw when the device is turned off. When you are not able to measure set to 0.4 for lights"
    },
    "standby_power_on": {
      "type": "number",
      "minimum": 0.05,
      "description": "Power draw when the device is turned on."
    },
    "sub_profile_select": {
      "type": "object",
      "description": "Configuration to automatically select a sub profile",
      "required": [
        "default"
      ],
      "properties": {
        "default": {
          "type": "string",
          "description": "Default profile to select when non of the matchers apply"
        },
        "matchers": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "enum": [
                  "attribute",
                  "entity_id",
                  "entity_registry",
                  "entity_state",
                  "integration",
                  "model_id"
                ]
              },
              "attribute": {
                "type": "string"
              },
              "map": {
                "type": "object"
              },
              "pattern": {
                "type": "string"
              },
              "property": {
                "type": "string"
              },
              "profile": {
                "type": "string"
              },
              "integration": {
                "type": "string"
              },
              "value": {},
              "model_id": {
                "type": "string"
              }
            },
            "required": [
              "type"
            ]
          },
          "description": "List of matchers which will be checked"
        }
      }
    }
  },
  "definitions": {
    "condition": {
      "type": "object",
      "properties": {
        "condition": {
          "type": "string",
          "enum": [
            "and",
            "or",
            "state",
            "numeric_state",
            "template"
          ]
        },
        "conditions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/condition"
          }
        }
      },
      "additionalProperties": true
    }
  }
}

=== xxddff/homeassistant-powercalc/profile_library/xiaomi/philips.light.sread3/model.json
{
  "calculation_strategy": "lut",
  "created_at": "2026-04-17T17:03:41Z",
  "device_type": "light",
  "measure_description": "Measured with utils/measure script",
  "measure_device": "IKEA INSPELNING smart plug",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 2,
    "SLEEP_TIME": 5,
    "VERSION": "v1.20.12:docker"
  },
  "name": "Mijia Philips Desk Lamp 3",
  "standby_power": 0.4
}
